Run started:2025-04-12 13:56:04.256908

Test results:
>> Issue: [B814:read] os.read
   Severity: High   Confidence: Medium
   Location: /home/blue/PyPIAgent/Dataset/study/unzip_benign/dockerfile_parse-2.0.1-py2.py3-none-any/dockerfile_parse/parser.py:199
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b814_read.html
198	            with self._open_dockerfile('rb') as dockerfile:
199	                content = b2u(dockerfile.read())
200	                if self.cache_content:

--------------------------------------------------
>> Issue: [B815:write] os.write
   Severity: High   Confidence: Medium
   Location: /home/blue/PyPIAgent/Dataset/study/unzip_benign/dockerfile_parse-2.0.1-py2.py3-none-any/dockerfile_parse/parser.py:218
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b815_write.html
217	            with self._open_dockerfile('wb') as dockerfile:
218	                dockerfile.write(u2b(content))
219	        except (IOError, OSError) as ex:

--------------------------------------------------

Code scanned:
	Total lines of code: 992
	Total lines skipped (#nosec): 0

Run metrics:
	Total issues (by severity):
		Undefined: 0.0
		Low: 0.0
		Medium: 0.0
		High: 2.0
	Total issues (by confidence):
		Undefined: 0.0
		Low: 0.0
		Medium: 2.0
		High: 0.0
Files skipped (0):
