metaprogramming_in_setup /home/blue/PyPIAgent/Dataset/study/unzip_benign/dockerfile_parse-2.0.1-py2.py3-none-any/dockerfile_parse/parser.py
0x20a8:$compile_call: compile(r
0x20f3:$compile_call: compile(r
0x213b:$compile_call: compile(r
0x21d0:$compile_call: compile(r
0x2244:$compile_call: compile(r
0x24c2:$compile_call: compile(r
0x7f2b:$compile_call: compile(r
0xa7b:$vars_call: vars f
0xf92:$vars_call: vars: 
metaprogramming_in_setup /home/blue/PyPIAgent/Dataset/study/unzip_benign/dockerfile_parse-2.0.1-py2.py3-none-any/dockerfile_parse/util.py
0x18d3:$vars_call: vars(v
0x1a37:$vars_call: vars(x
0x1cab:$vars_call: vars(x
